git-auto-update 2023-05-12T02:05:02+00:00

diff --git a/scripts/hosts/sol/wasabi-sync b/scripts/hosts/sol/wasabi-sync
--- a/scripts/hosts/sol/wasabi-sync
+++ b/scripts/hosts/sol/wasabi-sync
@@ -4,12 +4,19 @@ export RCLONE_CONFIG="${DOTFILES_PRIVATE}/wasabi/rclone.conf"
 
 PREFIX='wasabi:nullsum-sol'
 
-RET=0
+HAS_ERROR=
 
 rclone_sync() {
-    rclone sync "$@" -v
+    rclone sync "$@" -v || true
     NEW_RET=$?
-    [ $NEW_RET -gt $RET ] && RET=$NEW_RET
+    case "$NEW_RET" in
+        9)
+            # no files transferred
+            ;;
+        *)
+            echo "error: exit code ${NEW_RET}" >&2
+            HAS_ERROR=1
+    esac
 }
 
 rclone_sync /storage/Games \
@@ -27,4 +34,6 @@ rclone_sync /storage/Pictures \
     "${PREFIX}"/storage1/Pictures
 
 rclone size "${PREFIX}"
-exit $RET
+if [ -n "$HAS_ERROR" ]; then
+    exit 1
+fi
