git-auto-update 2019-08-22T14:01:27+00:00

diff --git a/scripts/commands/consul/consul-kv-nested b/scripts/commands/consul/consul-kv-nested
--- a/scripts/commands/consul/consul-kv-nested
+++ b/scripts/commands/consul/consul-kv-nested
@@ -48,4 +48,14 @@ if [ -t 0 ]; then
     fi
 else
     format_json
+    if [ "$#" -eq 0 ]; then
+        format_json
+    elif [ "$#" -eq 1 ]; then
+        key="$(echo "$1" | sed 's/\/$//')"
+        format_json | remove_prefix "$key"
+    else
+        show_usage >&2
+        echo 'error: too many arguments' >&2
+        exit 1
+    fi
 fi
