git-auto-update 2020-12-05T03:51:56+00:00

diff --git a/scripts/commands/Xorg/apply-display-calibration b/scripts/commands/Xorg/apply-display-calibration
--- a/scripts/commands/Xorg/apply-display-calibration
+++ b/scripts/commands/Xorg/apply-display-calibration
@@ -37,6 +37,10 @@ while true; do
                     AP///////wAQrHugUzg5MBEXAQSlNCB4Ou6Vo1RMmSYPUFShCACBQIGAqUCzANHAAQEBAQEBKDyAoHCwI0AwIDYABkQhAAAaAAAA/wBZTVlIMTM0TDA5OFMKAAAA/ABERUxMIFUyNDEyTQogAAAA/QAyPR5TEQAKICAgICAgAMk=)
                         PROFILE="$DOTFILES/icc/U2412M #1 2020-11-30 19-46 D6500 sRGB F-S XYZLUT+MTX.icc"
                         ;;
+                    # other desk - dell u2412m
+                    AP///////wAQrHqgU0RKMBEXAQOANCB46u6Vo1RMmSYPUFShCACBQIGAqUCzANHAAQEBAQEBKDyAoHCwI0AwIDYABkQhAAAaAAAA/wBZTVlIMTM0TDBKRFMKAAAA/ABERUxMIFUyNDEyTQogAAAA/QAyPR5TEQAKICAgICAgAAY=)
+                        PROFILE="$DOTFILES/icc/U2412M #1 2020-12-04 21-23 D6500 sRGB F-S XYZLUT+MTX.icc"
+                        ;;
                     # office - LG 34GK950F-B
                     AP///////wAebSd3/aoHAAMdAQS1UCF4n/Z1r05CqyYOUFQlSwBxQIGAgcCpwLMA0cCBANHP53xwoNCgKVAwIDoAIE8xAAAaTqtwuNGgQlCQYGQIIE8xAAAaAAAA/QAwkOHhUAEKICAgICAgAAAA/AAzNEdLOTUwRgogICAgApYCAyhxIwkGB0kQBAMBHxMSBRTjBcAA4wYFAW0aAAACBzCQAARhPmE+TtRwoNCgRlAwIDoAIE8xAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxnASeQAAAwAo6gUBhm8N3wCPgB8AnwVUAAIACQBmOAGGbw3vAC+AHwCfBUUAAgAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPaQ)
                         PROFILE="$DOTFILES/icc/DisplayPort-0 #1 2020-11-25 18-29 2.2 F-S XYZLUT+MTX.icc"
@@ -57,6 +61,11 @@ done
 
 
 clear_existing_calibration
+
+if [ -z "$PROFILE" ]; then
+    echo "error: no profile detected" >&2
+    exit 1
+fi
 
 echo "Profile: $PROFILE"
 dispwin -d1 "$PROFILE" 2> /dev/null
