git-auto-update 2021-03-18T21:51:54+00:00

diff --git a/scripts/commands/Xorg/apply-display-calibration b/scripts/commands/Xorg/apply-display-calibration
--- a/scripts/commands/Xorg/apply-display-calibration
+++ b/scripts/commands/Xorg/apply-display-calibration
@@ -29,6 +29,10 @@ while true; do
             ;;
         *)
             if [ $# -eq 1 ]; then
+                if ! [ -f "$1" ]; then
+                    echo 'error: profile not found' >&2
+                    exit 1
+                fi
                 PROFILE="$1"
             elif [ $# -eq 0 ]; then
                 # xrandr-edid $(xrandr-primary-output) | base64 -w0
@@ -41,9 +45,9 @@ while true; do
                     AP///////wAQrHqgU0RKMBEXAQOANCB46u6Vo1RMmSYPUFShCACBQIGAqUCzANHAAQEBAQEBKDyAoHCwI0AwIDYABkQhAAAaAAAA/wBZTVlIMTM0TDBKRFMKAAAA/ABERUxMIFUyNDEyTQogAAAA/QAyPR5TEQAKICAgICAgAAY=)
                         PROFILE="$DOTFILES/icc/U2412M #1 2020-12-04 21-23 D6500 sRGB F-S XYZLUT+MTX.icc"
                         ;;
-                    # office - LG 34GK950F-B
-                    AP///////wAebSd3/aoHAAMdAQS1UCF4n/Z1r05CqyYOUFQlSwBxQIGAgcCpwLMA0cCBANHP53xwoNCgKVAwIDoAIE8xAAAaTqtwuNGgQlCQYGQIIE8xAAAaAAAA/QAwkOHhUAEKICAgICAgAAAA/AAzNEdLOTUwRgogICAgApYCAyhxIwkGB0kQBAMBHxMSBRTjBcAA4wYFAW0aAAACBzCQAARhPmE+TtRwoNCgRlAwIDoAIE8xAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxnASeQAAAwAo6gUBhm8N3wCPgB8AnwVUAAIACQBmOAGGbw3vAC+AHwCfBUUAAgAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPaQ)
-                        PROFILE="$DOTFILES/icc/DisplayPort-0 #1 2020-11-25 18-29 2.2 F-S XYZLUT+MTX.icc"
+                    # office - LG 34GP83A-B
+                    AP///////wAebUt31PYBAAIfAQS1UCF4n/Z1r05CqyYOUFQhCQBxQIGAgcCpwLMA0cCBANHP2qdwUNWgNFCQIDowIE8xAAAaAAAA/QAwkOHhUAEKICAgICAgAAAA/ABMRyBVTFRSQUdFQVIKAAAA/wAxMDJOVEpKM1M3MjQKAnQCAzBxIwkHB0cQBAMBHxMSgwEAAOMFwADiAGrmBgUBYWE9bRoAAAIFMJAABGE9YT1O1HDQ0KAyUDAgOgAgTzEAABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7nASeQAAAwEUZjgBhm8N7wAvgB8AnwVFAAIACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuQ)
+                        PROFILE="$DOTFILES/icc/DisplayPort-0 #1 2021-03-18 17-33 sRGB F-S XYZLUT+MTX.icc"
                         ;;
                     # phobos - xps 13
                     AP///////wBNECEUAAAAADIYAQSlHRF4Dt5Qo1RMmSYPUFQAAAABAQEBAQEBAQEBAQEBAQEBzZGAoMAINHAwIDUAJqUQAAAYAAAAEAAAAAAAAAAAAAAAAAAAAAAA/gAwNVA3SIVMUTEzM1oxAAAAAAACQQMoABIAAAsBCiAgABs=)
