git-auto-update 2019-08-08T00:30:00+00:00

diff --git a/scripts/commands/Xorg/set-desktop-themes b/scripts/commands/Xorg/set-desktop-themes
--- a/scripts/commands/Xorg/set-desktop-themes
+++ b/scripts/commands/Xorg/set-desktop-themes
@@ -41,29 +41,17 @@ else
     if [ "$DPI" -le 138 ]; then
         BORDER_WIDTH=1
         CURSOR_SIZE=16
-        DUNST_GEOMETRY_Y=+18
+        DUNST_GEOMETRY=300x5-0
         DUNST_MAX_ICON_SIZE=64
         FONT_SIZE=9
         SCALING_FACTOR=1
-
-        if [ -n "$LARGE" ]; then
-            DUNST_GEOMETRY=300x5-0+28
-        else
-            DUNST_GEOMETRY=300x5-0+18
-        fi
     else
         BORDER_WIDTH=3
         CURSOR_SIZE=48
-        DUNST_GEOMETRY=800x5-0+44
+        DUNST_GEOMETRY=800x5-0
         DUNST_MAX_ICON_SIZE=128
         FONT_SIZE=10
         SCALING_FACTOR=2
-
-        if [ -n "$LARGE" ]; then
-            DUNST_GEOMETRY=300x5-0+56
-        else
-            DUNST_GEOMETRY=300x5-0+44
-        fi
     fi
 
     if [ -n "$LARGE" ]; then
@@ -73,7 +61,6 @@ fi
 
 # save settings
 cat > "$CURRENT_THEME" << EOF
-ANTIALIAS="$ANTIALIAS"
 BORDER_WIDTH="$BORDER_WIDTH"
 CURSOR_SIZE="$CURSOR_SIZE"
 DPI="$DPI"
@@ -116,12 +103,27 @@ xrandr --dpi $DPI
 termite-config-reload
 hsetroot -solid $(xrdb -query | grep '*background' | awk '{print $2}')
 
+# need to restart to ensure cursor size on status bar is updated
+i3 restart &> /dev/null || true
+
+# need retry logic due to slow i3 restarts
+for i in {1..10}; do
+    i3_topbar_height="$(i3-msg -t get_tree | jq '[.nodes[].nodes[].nodes[].geometry.height] | max')"
+    if [ -n "$i3_topbar_height" -a "$i3_topbar_height" -gt 0 ]; then
+        break
+    else
+        sleep 0.25
+    fi
+done
+
+if [ -z "$i3_topbar_height" -o "$i3_topbar_height" -eq 0 ]; then
+    echo error: cannot determine i3 topbar height >&2
+    exit 1
+fi
+
 pkill -9 dunst || true
 dunst \
     -font "$FONT_NAME $FONT_SIZE" \
     -frame_width "$BORDER_WIDTH" \
     -max_icon_size "$DUNST_MAX_ICON_SIZE" \
-    -geometry "$DUNST_GEOMETRY" &
-
-# need to restart to ensure cursor size on status bar is updated
-i3 restart &> /dev/null || true
+    -geometry "$DUNST_GEOMETRY+$i3_topbar_height" &
