git-auto-update 2019-03-17 13:58:06

diff --git a/scripts/bullshit/fuck b/scripts/bullshit/fuck
--- a/scripts/bullshit/fuck
+++ b/scripts/bullshit/fuck
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-play_it() {
-    openssl base64 -d << EOF | play -
+decode_audio() {
+    openssl base64 -d << EOF
 T2dnUwACAAAAAAAAAADSMXN7AAAAAE5HzgsBE09wdXNIZWFkAQE4AUSsAAAAAABPZ2dTAAAAAAAA
 AAAAANIxc3sBAAAAQbYICgP///5PcHVzVGFncx0AAABsaWJvcHVzIDEuMywgbGlib3B1c2VuYyAw
 LjIuMQIAAAAjAAAARU5DT0RFUj1vcHVzZW5jIGZyb20gb3B1cy10b29scyAwLjI6AAAARU5DT0RF
@@ -38,4 +38,11 @@ psjVBaiwAqVpHnoE4A4C7gY5Cw42xVj4x1FO1Jk=
 EOF
 }
 
-play_it > /dev/null 2>&1 &
+if command -v play > /dev/null; then
+    decode_audio | play - > /dev/null 2>&1 &
+elif command -v play > /dev/null; then
+    decode_audio | mpv - > /dev/null 2>&1 &
+else
+    echo 'error: requires either play (sox) or mpv' >&2
+    exit 1
+fi
diff --git a/scripts/bullshit/piss b/scripts/bullshit/piss
--- a/scripts/bullshit/piss
+++ b/scripts/bullshit/piss
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-play_it() {
-    openssl base64 -d << EOF | play -
+decode_audio() {
+    openssl base64 -d << EOF
 T2dnUwACAAAAAAAAAAAxHE4bAAAAAKtpCGMBE09wdXNIZWFkAQE4AUSsAAAAAABPZ2dTAAAAAAAA
 AAAAADEcThsBAAAAV22GFAP///5PcHVzVGFncx0AAABsaWJvcHVzIDEuMywgbGlib3B1c2VuYyAw
 LjIuMQIAAAAjAAAARU5DT0RFUj1vcHVzZW5jIGZyb20gb3B1cy10b29scyAwLjI6AAAARU5DT0RF
@@ -37,4 +37,11 @@ gODB/p2FDcPlN8kJ7+O9AjQCkMdcrzZyFDHmFv4AL7uwdp4OawRr
 EOF
 }
 
-play_it > /dev/null 2>&1 &
+if command -v play > /dev/null; then
+    decode_audio | play - > /dev/null 2>&1 &
+elif command -v play > /dev/null; then
+    decode_audio | mpv - > /dev/null 2>&1 &
+else
+    echo 'error: requires either play (sox) or mpv' >&2
+    exit 1
+fi
diff --git a/scripts/bullshit/shit b/scripts/bullshit/shit
--- a/scripts/bullshit/shit
+++ b/scripts/bullshit/shit
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-play_it() {
-    openssl base64 -d << EOF | play -
+decode_audio() {
+    openssl base64 -d << EOF
 T2dnUwACAAAAAAAAAABFrf5JAAAAAC+gsZMBE09wdXNIZWFkAQE4AUSsAAAAAABPZ2dTAAAAAAAA
 AAAAAEWt/kkBAAAA7Up79wP///5PcHVzVGFncx0AAABsaWJvcHVzIDEuMywgbGlib3B1c2VuYyAw
 LjIuMQIAAAAjAAAARU5DT0RFUj1vcHVzZW5jIGZyb20gb3B1cy10b29scyAwLjI6AAAARU5DT0RF
@@ -41,4 +41,11 @@ I0NiqT32UEpbekHavc7wcxJK52A8ZHZIn92W
 EOF
 }
 
-play_it > /dev/null 2>&1 &
+if command -v play > /dev/null; then
+    decode_audio | play - > /dev/null 2>&1 &
+elif command -v play > /dev/null; then
+    decode_audio | mpv - > /dev/null 2>&1 &
+else
+    echo 'error: requires either play (sox) or mpv' >&2
+    exit 1
+fi
diff --git a/scripts/syncthing/toto b/scripts/syncthing/toto
--- a/scripts/syncthing/toto
+++ b/scripts/syncthing/toto
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-you_typoed() {
-    base64 -d << EOF | play -
+decode_audio() {
+    base64 -d << EOF
 T2dnUwACAAAAAAAAAABSiqcVAAAAAEOz0p8BE09wdXNIZWFkAQE4AYC7AAAAAABPZ2dTAAAAAAAA
 AAAAAFKKpxUBAAAAXYbMlwP///5PcHVzVGFncx0AAABsaWJvcHVzIDEuMywgbGlib3B1c2VuYyAw
 LjIuMQIAAAAjAAAARU5DT0RFUj1vcHVzZW5jIGZyb20gb3B1cy10b29scyAwLjI6AAAARU5DT0RF
@@ -137,4 +137,11 @@ v9NkU4Pxp6UcUgTYNFrT1G4AjksEbEsAjtAAGKYIB2MkYf6/2R5U/KE=
 EOF
 }
 
-you_typoed > /dev/null 2>&1 &
+if command -v play > /dev/null; then
+    decode_audio | play - > /dev/null 2>&1 &
+elif command -v play > /dev/null; then
+    decode_audio | mpv - > /dev/null 2>&1 &
+else
+    echo 'error: requires either play (sox) or mpv' >&2
+    exit 1
+fi
