git-auto-update 2020-11-18T17:14:49+00:00

diff --git a/scripts/commands/python/py b/scripts/commands/python/py
--- a/scripts/commands/python/py
+++ b/scripts/commands/python/py
@@ -1,3 +1,31 @@
 #!/usr/bin/env sh
-export PYTHONSTARTUP=$DOTFILES/python/pythonstartup
-exec python3 -q "$@"
+export PYTHONSTARTUP="$DOTFILES/python/pythonstartup"
+case $# in
+    0)
+        exec python3 -q "$@"
+        ;;
+    1)
+        DATA="$(cat "$PYTHONSTARTUP")"
+        COMMANDS="$(printf %s "$1" | base64)"
+        python3 << EOF
+$DATA
+command = base64.b64decode('$COMMANDS').decode()
+try:
+    compiled = compile(command, '<string>', 'eval')
+    func = eval
+except SyntaxError:
+    compiled = compile(command, '<string>', 'exec')
+    func = exec
+
+ret = func(compiled)
+if ret is not None:
+    if isinstance(ret, bytes):
+        sys.stdout.buffer.write(ret)
+    else:
+        print(ret)
+EOF
+        ;;
+    *)
+        echo 'error: unexpected arguments' >&2
+        exit 1
+esac
