git-auto-update 2020-11-27T21:23:41+00:00

diff --git a/full-update/00-dotfiles b/full-update/00-dotfiles
--- a/full-update/00-dotfiles
+++ b/full-update/00-dotfiles
@@ -1,12 +1,62 @@
 #!/usr/bin/env sh
+VERBOSE=
+PROVISION=
+while $# -gt 0; do
+    case "$1" in
+        -v)
+            VERBOSE=1
+            shift
+            ;;
+        --provision)
+            PROVISION=1
+            shift
+            ;;
+        *)
+            echo 'error: unrecognized arguments' >&2
+            exit 1
+    esac
+done
+
 MAGENTA='\033[1;35m'
 RESET='\033[0m'
+
+update_non_user() {
+    dotfiles_root="$1"
+    tag="$2"
+    backup_root="$dotfiles_root/non-user/$tag"
+    if [ -d "$backup_root" ]; then
+        for source in $(find "$backup_root" -type f); do
+            target=${source#$backup_root}
+            if test -f "$target" || [ "$tag" != 'common' ]; then
+                if ! diff "$source" "$target" > /dev/null 2>&1 ; then
+                    echo Syncing "$target"
+                    sudo mkdir -p "$(dirname "$target")"
+                    sudo cp "$source" "$target"
+                elif [ -n "$VERBOSE" ]; then
+                    echo Found "$tag" "$target"
+                fi
+            fi
+        done
+    fi
+}
 
 update_repo() {
     dotfiles_root="$2"
     if [ -d "$dotfiles_root/.git" ]; then
         printf "${MAGENTA}Updating $1 ($dotfiles_root)...${RESET}\n"
         git auto-update "$dotfiles_root"
+    fi
+
+    if [ -n "$PROVISION" ]; then
+        # non-user files
+        if command -v sudo > /dev/null; then
+            update_non_user "$dotfiles_root" common
+            update_non_user "$dotfiles_root" "$(hostname)"
+
+            if command -v pacman > /dev/null; then
+                update_non_user "$dotfiles_root" _archlinux
+            fi
+        fi
     fi
 }
 
