Ignore pipewire 1:1.4.3-1 due to mpv stuttering https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4713

diff --git a/full-update/10-arch-linux b/full-update/10-arch-linux
--- a/full-update/10-arch-linux
+++ b/full-update/10-arch-linux
@@ -33,7 +33,17 @@ if ! command -v yay > /dev/null 2>&1; then
 fi
 
 log 'Updating packages'
-yay -Syu --noconfirm --devel
+yay -Sy
+
+# ignore pipewire 1:1.4.3-1 due to mpv stutter https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4713
+pipewire_ver="$(pacman -Sdp --print-format '%v' pipewire)"
+if [ "$pipewire_ver" != '1:1.4.3-1' ]; then
+    printf 'error: unexpected pipewire version (%s)\n' "$pipewire_ver" >&2
+    printf 'modify this script to resolve.' >&2
+    exit 1
+fi
+yay -Su --noconfirm --devel \
+    --ignore libpipewire,pipewire,pipewire-alsa,pipewire-audio,pipewire-jack,pipewire-pulse
 
 if command -v pkgfile > /dev/null; then
     log 'Updating file cache'
