git-auto-update 2023-08-14T15:36:49+00:00

diff --git a/full-update/20-gtk4 b/full-update/20-gtk4
--- a/full-update/20-gtk4
+++ b/full-update/20-gtk4
@@ -1,12 +1,14 @@
 #!/usr/bin/env sh
 if command -v gtk4-launch > /dev/null; then
     DEST=~/.config/'gtk-4.0'
-    if [ -d "$DEST" ] && [ "$(readlink -f "$DEST")" != "$DOTFILES/gtk-4.0" ]; then
-        echo 'error: unexpectedly exists' >&2
-        exit 1
+    if [ -d "$DEST" ]; then
+        if [ "$(readlink -f "$DEST")" != "$DOTFILES/gtk-4.0" ]; then
+            echo 'error: unexpectedly exists' >&2
+            exit 1
+        fi
     else
         mkdir -p ~/.config
-        ln -sf "$DOTFILES/gtk-4.0" "$DEST"
+        ln -sfT "$DOTFILES/gtk-4.0" "$DEST"
     fi
 else
     rm -rf "$DEST"
