git-auto-update 2020-08-06T13:23:04+00:00

diff --git a/full-update/30-nvm b/full-update/30-nvm
--- a/full-update/30-nvm
+++ b/full-update/30-nvm
@@ -4,7 +4,32 @@ set -e
 XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
 INSTALL_DIR="${XDG_DATA_DIR}/nvm"
 
-if ! [ -d "$INSTALL_DIR" ]; then
+show_help() {
+    cat << EOF
+usage:
+    -f, --force     force installation
+    --help          show help and exit
+EOF
+}
+
+FORCE=
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -f|--force)
+            FORCE=1
+            shift
+            ;;
+        --help)
+            show_help
+            exit
+            ;;
+        *)
+            echo 'error: unknown argument(s)' >&2
+            exit 1
+    esac
+done
+
+if [ -z "$FORCE" ] && ! [ -d "$INSTALL_DIR" ]; then
     exit
 fi
 
