git-auto-update 2019-03-11 23:34:00

diff --git a/scripts/terminal/extract b/scripts/terminal/extract
--- a/scripts/terminal/extract
+++ b/scripts/terminal/extract
@@ -4,9 +4,9 @@ set -e
 show_help() {
     cat << EOF
 usage: extract [-i] [-r] [-d] FILE [FILE ...]
-	-c	create a child directory for each archive and extract there
-	-p	parent directory to extract to. defaults to directory where archive resides
-	-r	remove archive after successful extraction
+    -c  create a child directory for each archive and extract there
+    -p  parent directory to extract to. defaults to directory where archive resides
+    -r  remove archive after successful extraction
 EOF
 }
 
@@ -50,6 +50,13 @@ while true; do
         *)
             break
     esac
+done
+
+for filename in "$@"; do
+    if ! [ -e "$filename" ]; then
+        echo "error: file not found \"$filename\"" >&2
+        exit 1
+    fi
 done
 
 for filename in "$@"; do
