git-auto-update 2020-11-24T17:38:46+00:00

diff --git a/scripts/terminal/lower b/scripts/terminal/lower
--- a/scripts/terminal/lower
+++ b/scripts/terminal/lower
@@ -1,2 +1,15 @@
 #!/usr/bin/env sh
-exec tr '[:upper:]' '[:lower:]'
+_lower() {
+    tr '[:upper:]' '[:lower:]'
+}
+
+if [ $# -gt 0 ]; then
+    if [ $# -eq 1 ]; then
+        printf '%s' "$1" | _lower
+    else
+        echo 'error: unexpected arguments' >&2
+        exit 1
+    fi
+else
+    _lower
+fi
diff --git a/scripts/terminal/upper b/scripts/terminal/upper
--- a/scripts/terminal/upper
+++ b/scripts/terminal/upper
@@ -1,2 +1,15 @@
 #!/usr/bin/env sh
-exec tr '[:lower:]' '[:upper:]'
+_upper() {
+    tr '[:lower:]' '[:upper:]'
+}
+
+if [ $# -gt 0 ]; then
+    if [ $# -eq 1 ]; then
+        printf '%s' "$1" | _upper
+    else
+        echo 'error: unexpected arguments' >&2
+        exit 1
+    fi
+else
+    _upper
+fi
