git-auto-update 2021-05-09T15:40:49+00:00

diff --git a/scripts/terminal/preview b/scripts/terminal/preview
--- a/scripts/terminal/preview
+++ b/scripts/terminal/preview
@@ -6,7 +6,10 @@ default_preview() {
     bat -r :1024 --color=always --plain -- "$1"
 }
 
-if [ -d "$1" ]; then
+if [ $# -eq 0 ]; then
+    echo 'error: missing argument' >&2
+    exit 1
+elif [ -d "$1" ]; then
     cd "$1" || exit 1
     fd --color=always --maxdepth=1
 else
