git-auto-update 2022-09-20T12:09:28+00:00

diff --git a/scripts/terminal/sedmv b/scripts/terminal/sedmv
--- a/scripts/terminal/sedmv
+++ b/scripts/terminal/sedmv
@@ -7,6 +7,10 @@ for f in "$@"; do
     base="$(basename "$f")"
     new="$(printf %s "$base" | sed "$pattern")"
     if [ "$new" != "$base" ]; then
-        mv --no-clobber "$f" "$dir/$new"
+        if [ -e "$new" ]; then
+            printf 'error: target exists "%s" (original "%s")\n' "$new" "$base" >&2
+        else
+            mv --no-clobber "$f" "$dir/$new"
+        fi
     fi
 done
