git-auto-update 2021-12-26T16:46:35+00:00

diff --git a/scripts/backup-dvd b/scripts/backup-dvd
--- a/scripts/backup-dvd
+++ b/scripts/backup-dvd
@@ -3,25 +3,32 @@ set -e
 
 DEVICE="$1"
 DESTINATION="$2"
+LABEL="$3"
 
-if ! [ -f "$DEVICE" ]; then
+if ! [ -e "$DEVICE" ]; then
     cat >&2 << EOF
 usage: INFILE OUTDIR
 EOF
     exit 1
 fi
 
-if [ -e "$DESTINATION" ]; then
-    echo 'error: destination exists' >&2
+if [ -z "$LABEL" ]; then
+    LABEL="$(blkid -o value -s LABEL "$DEVICE")"
+fi
+
+OUTFILE="${DESTINATION}/${LABEL}.iso"
+LOGFILE="${DESTINATION}/${LABEL}.log"
+
+if [ -e "$OUTFILE" ] || [ -e "$LOGFILE" ]; then
+    echo 'error: OUTFILE and/or LOGFILE already exists' >&2
     exit 1
 fi
-mkdir -p "$DESTINATION"
 
 echo 'Reading without retry ...'
-ddrescue --sector-size=2048 --verbose --no-scape "$DEVICE" "${DESTINATION}/disc.iso" "${DESTINATION}/rescue.log"
+ddrescue --sector-size=2048 --verbose --no-scrape "$DEVICE" "${OUTFILE}" "${LOGFILE}"
 
 echo 'Reading with retry ...'
-ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 "$DEVICE" "${DESTINATION}/disc.iso" "${DESTINATION}/rescue.log"
+ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 "$DEVICE" "${OUTFILE}" "${LOGFILE}"
 
 echo 'Reading with retry and reversed ...'
-ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 --reverse "$DEVICE" "${DESTINATION}/disc.iso" "${DESTINATION}/rescue.log"
+ddrescue --sector-size=2048 --verbose --idirect --retry-passes=5 --reverse "$DEVICE" "${OUTFILE}" "${LOGFILE}"
