git-auto-update 2024-07-07T01:04:35+00:00

diff --git a/scripts/commands/kwin_wayland/tmux-scratchpad b/scripts/commands/kwin_wayland/tmux-scratchpad
--- a/scripts/commands/kwin_wayland/tmux-scratchpad
+++ b/scripts/commands/kwin_wayland/tmux-scratchpad
@@ -1,4 +1,18 @@
 #!/bin/sh
-while true; do 
+MAX_ATTEMPTS=60
+ATTEMPTS=$MAX_ATTEMPTS
+while [ "${ATTEMPTS}" -gt 0 ]; do 
+    START="$(date +%s)"
     foot --title tmux-scratchpad --app-id tmux-scratchpad -- zsh -ic 'tmux-attach'
+    END="$(date +%s)"
+    
+    if [ "$((END - START))" -le 2 ]; then
+        ATTEMPTS=$((ATTEMPTS - 1))
+        echo 'warning: application exited too quicky' >&2
+        sleep 1
+    else
+        ATTEMPTS=$MAX_ATTEMPTS
+    fi
 done
+echo 'error: too many attempts' >&2
+exit 1
